services:
  web:
    build:
      context: .
      network: host
    container_name: todo-web
    command: gunicorn --bind 0.0.0.0:8000 todo_project.wsgi:application
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: todo-db
    environment:
      POSTGRES_DB: vkinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 619620qazwsx
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: todo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:

networks:
  app-network:
