services:
  web:
    build:
      context: .
      network: host
    container_name: todo-web
    command: gunicorn --bind 0.0.0.0:8000 todo_project.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: todo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web
volumes:
  static_volume:
